banking_dbt:
  outputs:
    dev:
      type: snowflake
      account: PNOZNWQ-LL71699
      user: VANTHANHNGUYENB68
      password: "123456789@Thanh"
      role: ACCOUNTADMIN
      database: BANKING
      warehouse: COMPUTE_WH
      schema: ANALYTICS
      threads: 4
  target: dev