version: 2

sources:
  - name: raw
    database: BANKING
    schema: RAW
    tables:
      - name: customers
        description: "Raw customers data ingested from MinIO into Snowflake RAW layer"
      - name: accounts
        description: "Raw accounts data ingested from MinIO into Snowflake RAW layer"
      - name: transactions
        description: "Raw transactions data ingested from MinIO into Snowflake RAW layer"
